export const SCORING_THRESHOLDS = {
  weights: {
    fundamentals: 0.4,
    risk: 0.25,
    sentiment: 0.2,
    technicals: 0.15,
  },
  fundamentals: {
    peLow: 15,
    peHigh: 35,
    marginHigh: 0.2,
    marginLow: 0,
    revenueMin: 0,
    peLowBonus: 2,
    peHighPenalty: -2,
    marginHighBonus: 1.5,
    marginLowPenalty: -2,
    revenueBonus: 0.5,
  },
  risk: {
    betaLow: 1.0,
    betaHigh: 1.5,
    deLow: 1.0,
    deHigh: 2.0,
    betaLowBonus: 2,
    betaHighPenalty: -2,
    deLowBonus: 2,
    deHighPenalty: -2,
  },
  technicals: {
    rsiLow: 30,
    rsiHigh: 70,
    rsiLowBonus: 2,
    rsiHighPenalty: -2,
    ma200Bonus: 1,
    ma200Penalty: -1,
  },
  sentiment: {
    newsHighCount: 5,
    newsZeroCount: 0,
    newsHighBonus: 1,
    newsZeroPenalty: -1,
  },
  tiers: [
    { threshold: 9.0, rating: "Strong Buy" },
    { threshold: 8.0, rating: "Highly Recommended" },
    { threshold: 7.0, rating: "Good Potential" },
    { threshold: 6.0, rating: "Moderate Potential" },
    { threshold: 5.0, rating: "High Risk" },
    { threshold: 4.0, rating: "Very High Risk" },
  ],
  defaultRating: "Pass",
  baseScores: {
    fundamentals: 5,
    risk: 5,
    technicals: 5,
    sentiment: 5,
  },
};
