export const SCORING_THRESHOLDS = {
  weights: {
    fundamentals: 0.4,
    risk: 0.25,
    sentiment: 0.2,
    technicals: 0.15,
  },
  fundamentals: {
    peLow: 15,
    peHigh: 35,
    marginHigh: 0.2,
    marginLow: 0,
    revenueMin: 0,
    peLowBonus: 1.0,
    peHighPenalty: -1.5,
    marginHighBonus: 1.0,
    marginLowPenalty: -2.0,
    revenueBonus: 0.5,
  },
  risk: {
    betaLow: 1.0,
    betaHigh: 1.5,
    deLow: 1.0,
    deHigh: 2.0,
    betaLowBonus: 1.0,
    betaHighPenalty: -1.5,
    deLowBonus: 1.0,
    deHighPenalty: -1.5,
  },
  technicals: {
    rsiLow: 30,
    rsiHigh: 70,
    rsiLowBonus: 1.0,
    rsiHighPenalty: -1.5,
    ma200Bonus: 0.8,
    ma200Penalty: -1.5,
  },
  sentiment: {
    newsHighCount: 5,
    newsZeroCount: 0,
    newsHighBonus: 0.8,
    newsZeroPenalty: -1.5,
  },
  tiers: [
    { threshold: 9.0, rating: "Strong Buy" },
    { threshold: 8.0, rating: "Highly Recommended" },
    { threshold: 7.0, rating: "Good Potential" },
    { threshold: 6.0, rating: "Moderate Potential" },
    { threshold: 5.0, rating: "High Risk" },
    { threshold: 4.0, rating: "Very High Risk" },
  ],
  defaultRating: "Pass",
  baseScores: {
    fundamentals: 7.5,
    risk: 7.5,
    technicals: 7.5,
    sentiment: 7.5,
  },
};
